# Generated by Django 4.2.30 on 2026-04-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField()),
                ('mode', models.CharField(choices=[('beginner', 'Beginner'), ('balanced', 'Balanced'), ('advanced', 'Advanced')], default='balanced', max_length=20)),
                ('explanation', models.TextField()),
                ('steps', models.JSONField(default=list)),
                ('question', models.TextField()),
                ('file_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
