# Generated by Django 4.2.30 on 2026-04-24 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('mode', models.CharField(default='balanced', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_input', models.TextField()),
                ('file_type', models.CharField(blank=True, max_length=50, null=True)),
                ('intent', models.CharField(choices=[('learn_topic', 'Learn Topic'), ('solve_question', 'Solve Question'), ('quiz_me', 'Quiz Me'), ('homework', 'Homework'), ('revise', 'Revise'), ('explain_again', 'Explain Again')], default='learn_topic', max_length=30)),
                ('response_type', models.CharField(choices=[('learn', 'Learn'), ('solve', 'Solve'), ('quiz', 'Quiz'), ('homework', 'Homework'), ('revise', 'Revise')], default='learn', max_length=20)),
                ('mode', models.CharField(default='balanced', max_length=20)),
                ('explanation', models.TextField(blank=True)),
                ('steps', models.JSONField(default=list)),
                ('hint', models.TextField(blank=True)),
                ('solution', models.TextField(blank=True)),
                ('example', models.TextField(blank=True)),
                ('questions', models.JSONField(default=list)),
                ('student_attempt', models.TextField(blank=True)),
                ('evaluation', models.JSONField(default=dict)),
                ('improved_explanation', models.TextField(blank=True)),
                ('resources', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.conversation')),
            ],
        ),
    ]
