# Generated by Django 4.2.30 on 2026-04-24 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_conversation_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LearningHistory',
            new_name='Learning',
        ),
    ]
