# Generated by Django 4.2.30 on 2026-04-25 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_learninghistory_learning'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='lesson_structure',
            field=models.JSONField(default=dict),
        ),
    ]
