# Generated by Django 4.2.30 on 2026-04-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_message_lesson_structure'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('main_topic', models.CharField(max_length=255)),
                ('topics', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TopicProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('topic', models.CharField(max_length=255)),
                ('attempts', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('accuracy', models.FloatField(default=0.0)),
                ('difficulty_level', models.CharField(default='easy', max_length=20)),
                ('weak_areas', models.JSONField(default=list)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='hint_levels',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='message',
            name='mistake_analysis',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='message',
            name='next_recommended_topic',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='message',
            name='topic_progress',
            field=models.JSONField(default=dict),
        ),
    ]
